GET http://localhost:3000/media
###

GET http://localhost:3000/media/65656d2f4e2ca7ba4ccb0215
###

POST http://localhost:3000/media
Content-Type: application/json

{
    "id": "123",
    "title": "Hello",
    "genre": "Horror",
    "description": "Bad TV Show",
    "isLiked": 1
}

###
DELETE http://localhost:3000/media/65658c37116caef698c5eb4a

###
GET http://localhost:3000/media/6565609f6a9eb0b4ed0e1a33


###
PATCH http://localhost:3000/media/65658c37116caef698c5eb4a
Content-Type: application/json

{
    "title": "Apples",
    "isLiked": "1"
}
